pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      # - check-success=Test
      - check-success=Test@ubuntu-latest
      - check-success=Test@windows-latest
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
    actions:
      merge:
        method: rebase
