allowBuilds:
  '@parcel/watcher': set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
overrides:
  handlebars: "^4.7.9"
  flatted: "^3.4.2"
  rollup: "^4.59.0"
